<?=$this->getMessagesBlock()->getGroupedHtml() ?>
<p class="left"><a class="login-trigger signin-modal" data-modal="modal-login"><span><?=$this->__('LOGIN')?></span></a></p>

<div class="md-modal md-effect-7" id="modal-login">
	<div class="md-content">
			<div class="md-modal-header">
				<button type="button" class="close">&times;</button>
				<h4><?=$this->__('Login to your Account')?></h4>
			</div>	
			<div class="md-content-wrapper">
				<form action="<?=$this->getPostActionUrl() ?>" method="post" id="login-form">
		      		<?=$this->getBlockHtml('formkey'); ?>
			        <div>
						<ul class="form-list">
							<li>
								<label for="email" class="required"><em>*</em><?=$this->__('Email Address') ?></label>
								<div class="input-box">
									<input type="text" name="login[username]" value="<?=$this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?=$this->__('Email Address') ?>" />
								</div>
							</li>
						<li>
							<label for="pass" class="required"><em>*</em><?=$this->__('Password') ?></label>
							<div class="input-box">
								<input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?=$this->__('Password') ?>" />
							</div>
						</li>
						
						</ul>				
					</div>
					<input name="context" type="hidden" value="checkout" />
				</form>
				
				<?=$this->getChildhtml('forgotPassword');?>
			</div>
			<div class="md-modal-footer">
				<div id="login-button-set">
					<a href="<?=$this->getForgotPasswordUrl() ?>" class="f-left restore-account"><?=$this->__('Forgot Your Password?') ?></a>	        
					<button type="button" class="btn btn-primary"><span><span><?=$this->__('Login') ?></span></span></button>
				</div>	
				<div id="forgotpassword-button-set" style="display:none">		        	
		        	<p class="back-link"><a href="<?=$this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?=$this->__('Back to Login') ?></a></p>
		        	<button type="button" title="<?=$this->__('Submit') ?>" class="btn"><span><span><?=$this->__('Submit') ?></span></span></button>
    			</div>
			</div>
	</div>
</div>
<div class="md-overlay"></div>	
<script type="text/javascript">
    //<![CDATA[
        var dataForm1 = new VarienForm('login-form', true);
    //]]>
</script>
