<?php
/**
 * @see Mage_Checkout_Block_Agreements
 */
?>

<?php if (!$this->getAgreements()) return; ?>
<form action="" id="checkout-agreements" onsubmit="return false;">
	<ol class="checkout-agreements">
	<?php foreach ($this->getAgreements() as $_a): ?>
		<li>
			<div id="agreement-block-<?=$_a->getId();?>" class="agreement-content <?php if (Mage::helper('wsu_opc')->getTermsType()):?>hidden<?php endif?>"<?=($_a->getContentHeight() ? ' style="height:' . $_a->getContentHeight() . '"' : '')?>>
				<?php if ($_a->getIsHtml()):?>
					<?=$_a->getContent() ?>
				<?php else:?>
					<?=nl2br($this->htmlEscape($_a->getContent())) ?>
				<?php endif; ?>
			</div>
			<p class="agree">
				<input type="checkbox" id="agreement-<?=$_a->getId()?>" name="agreement[<?=$_a->getId()?>]" value="1" title="<?=$this->htmlEscape($_a->getCheckboxText()) ?>" class="checkbox" />
				<a class="view-agreement" data-id="<?=$_a->getId();?>">
					<span><?=($_a->getIsHtml() ? $_a->getCheckboxText() : $this->htmlEscape($_a->getCheckboxText()) )?></span> <?=$this->__('(click to read)')?>
				</a>
			</p>
		</li>
	<?php endforeach; ?>
	</ol>
</form>

<?php if (Mage::helper('wsu_opc')->getTermsType()):?>
	<!-- Modal -->
	<div class="modal fade" id="agreement-dialog" tabindex="-1" role="dialog" aria-labelledby="agreement-title" aria-hidden="true">
		<div class="modal-header">
			<span class="close">&times;</span>
			<h4 class="modal-title" id="agreement-title"></h4>
		</div>
		<div class="modal-body" id="agreement-modal-body"></div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal"><span><span><?=$this->__('Close')?></span></span></button>        
		</div>
	</div>
<?php endif;?>