<div class="comment-block">
<h3><?=$this->__('Comment')?><span class='expand_plus'></span></h3>
    <div  class="collapse-block hidden">
	    <div class="comment">
	        <div class="comment-form">
	            <div class="input-box">
	                <textarea class="input-text" id="customer_comment" name="customer_comment"></textarea>
	            </div>
	        </div>
	    </div>
	</div>
</div>
