<?php
$cp_id = $this->getCouponCode();
/*  was thinkin maybe a time that the code would change the shipping... but the discount is apply to the cart .. so maybe not.. well come back to 
if(strlen($cp_id)){
	$oCoupon = Mage::getModel('salesrule/coupon')->load($cp_id, 'code');
	$oRule = Mage::getModel('salesrule/rule')->load($oCoupon->getRuleId());
	var_dump($oRule->getData());
}
*/
$loading = '<div class="opc-ajax-loader" style="display:none;"><div class="loader"><div class="outer"></div><div class="inner"></div></div></div>';
?>
<form id="opc-discount-coupon-form" action="<?=$this->getUrl('checkout/cart/couponPost', array('_secure' => $this->getRequest()->isSecure())) ?>" method="post">
    <div class="discount">
        <div class="discount-form">
            <label for="coupon_code"><?=$this->__('Enter your coupon code:') ?></label>            
            <div class="input-box">
                <input class="input-text" id="coupon_code" type="text" name="coupon_code" value="<?=$this->htmlEscape($cp_id) ?>" autocomplete="off"/>
            </div>
            <div class="buttons-set">
                <button type="button" title="<?=$this->__('Apply') ?>" class="button apply-coupon"  value="<?=$this->__('Apply') ?>"><span><span><?=$this->__('Apply') ?></span></span></button>
                <?php if(strlen($cp_id)): ?>
                    &nbsp; <button type="button" title="<?=$this->__('Cancel') ?>" class="button remove-coupon right"  value="<?=$this->__('Cancel') ?>"><span><span><?=$this->__('Cancel') ?></span></span></button>
                <?php endif;?>
            </div>
        </div>
    </div>
</form>
<?=$loading?>