<?=$this->getMessagesBlock()->getGroupedHtml() ?>
<p class="text-login">
	<?=$this->__('Already registered?') ?>
	<a href="#" id="trig_login_form"><?=$this->__('LOGIN HERE')?></a>
</p>
<!-- Modal -->
<div class="modal fade" id="login_form_modal" >
	<div class="modal-header">
		<span class="close" >&times;</span>
		<h4 class="modal-title" id="myModalLabel"><?=$this->__('Login to your Account')?></h4>
	</div>
	<div class="modal-body">
		<form action="<?=$this->getPostActionUrl() ?>" method="post" id="login-form">
			<?=$this->getBlockHtml('formkey'); ?>
			<div>
				<ul class="form-list">
					<li>
						<label for="email" class="required"><em>*</em><?=$this->__('Email Address') ?></label>
						<div class="input-box">
							<input type="text" name="login[username]" value="<?=$this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?=$this->__('Email Address') ?>" />
						</div>
					</li>
					<li>
						<label for="pass" class="required"><em>*</em><?=$this->__('Password') ?></label>
						<div class="input-box">
							<input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?=$this->__('Password') ?>" />
						</div>
					</li>
				</ul>				
			</div>
			<span id="login_helper"><?=$this->getChildHtml('form.additional.info');?></span>
						
			
			<input name="context" type="hidden" value="checkout" />
		</form>
		
		<?=$this->getChildhtml('forgotPassword');?>
		
	</div>
	<div class="modal-footer">
		<div id="login-button-set">
			<a href="<?=$this->getForgotPasswordUrl() ?>" class="f-left restore-account"><?=$this->__('Forgot Your Password?') ?></a>	        
			<button type="button" class="btn btn-primary"><span><span><?=$this->__('Login') ?></span></span></button>
		</div>	
		<div id="forgotpassword-button-set" style="display:none">		        	
			<p class="back-link"><a href="<?=$this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?=$this->__('Back to Login') ?></a></p>
			<button type="button" title="<?=$this->__('Submit') ?>" class="btn"><span><span><?=$this->__('Submit') ?></span></span></button>
		</div>
	</div>
</div>
	
	
	
<script type="text/javascript">
    //<![CDATA[
        var dataForm1 = new VarienForm('login-form', true);
    //]]>
</script>
<div class="clear move-columns"></div>


