<script type="text/javascript">
//<![CDATA[
    var quoteBaseGrandTotal = <?=(float)$this->getQuoteBaseGrandTotal(); ?>;
    var checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
    var payment = new Payment('co-payment-form', '<?=$this->getUrl('checkout/onepage/savePayment', array('_secure' => $this->getRequest()->isSecure())) ?>');
    var lastPrice;
//]]>
</script>

    <fieldset id="checkout-payment-method-load">
        <?=$this->getChildHtml('methods') ?>
    </fieldset>

<div class="tool-tip" id="payment-tool-tip" style="display:none;">
    <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?=$this->__('Close') ?>"><?=$this->__('Close') ?></a></div>
    <div class="tool-tip-content"><img src="<?=$this->getSkinUrl('images/cvv.gif') ?>" alt="<?=$this->__('Card Verification Number Visual Reference') ?>" title="<?=$this->__('Card Verification Number Visual Reference') ?>" /></div>
</div>
<script type="text/javascript">
//<![CDATA[
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-560)+'px'//,
                //left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
    payment.currentMethod = "<?=$this->getChild('methods')->getSelectedMethodCode() ?>";
//]]>
</script>
