<form action="<?=$this->getUrl('*/*/forgotpasswordpost', array('_secure' => $this->getRequest()->isSecure())) ?>" method="post" id="form-validate-email" style="display:none">
<?=$this->getMessagesBlock()->getGroupedHtml() ?>    
       
        <p><?=$this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
        <ul class="form-list">
            <li>
                <label for="email_address" class="required"><em>*</em><?=$this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?=$this->htmlEscape($this->getEmailValue()) ?>" />
                </div>
            </li>
        </ul>
       
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm2 = new VarienForm('form-validate-email', true);
//]]>
</script>
