<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
?>

<?php
    // Check if current Magento version includes Persistent Shopping Cart Extension
    $isPersistantShoppingCartEnabled = Mage::getStoreConfigFlag('persistent/options/enabled');
    $isContextCheckout = 0;
    if ($isPersistantShoppingCartEnabled) {
        $accountUrl = Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl());
        $isContextCheckout = Mage::helper('checkout')->isContextCheckout();
    } else {
        $accountUrl = $this->getCreateAccountUrl();
    }
?>

<div class="account-login">
    <div class="page-title">
        <h1><?=$this->__('Login or Create an Account') ?></h1>
    </div>
    <?=$this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?=$this->getPostActionUrl() ?>" method="post" id="login-form">
    	<?=$this->getBlockHtml('formkey'); ?>
        <div class="col2-set">
            <div class="col-1 new-users">
                <div class="content">
                    <h2><?=$this->__('New Customers') ?></h2>
                    <p><?=$this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
                </div>
            </div>
            <div class="col-2 registered-users">
                <div class="content">
                    <h2><?=$this->__('Registered Customers') ?></h2>
                    <p><?=$this->__('If you have an account with us, please log in.') ?></p>
                    <ul class="form-list">
                        <li>
                            <label for="email" class=""><em>*</em><?=$this->__('Email Address/Username') ?></label>
                            <div class="input-box">
                                <input type="text" name="login[username]" value="<?=$this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?=$this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="required"><em>*</em><?=$this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?=$this->__('Password') ?>" />
                            </div>
                        </li>
                        <?=$this->getChildHtml('persistent.remember.me'); ?>
                    </ul>
                    <?=$this->getChildHtml('persistent.remember.me.tooltip'); ?>
                    <p class="required"><?=$this->__('* Required Fields') ?></p>
                </div>
            </div>
        </div>
        <div class="col2-set">
            <div class="col-1 new-users">
                <div class="buttons-set">
                    <button type="button" title="<?=$this->__('Create an Account') ?>" class="button" onclick="window.location='<?=$accountUrl ?>';"><span><span><?=$this->__('Create an Account') ?></span></span></button>
                </div>
            </div>
            <div class="col-2 registered-users">
                <div class="buttons-set">
                    <a href="<?=$this->getForgotPasswordUrl() ?>" class="f-left"><?=$this->__('Forgot Your Password?') ?></a>
                    <button type="submit" class="button" title="<?=$this->__('Login') ?>" name="send" id="send2"><span><span><?=$this->__('Login') ?></span></span></button>
                </div>
            </div>
        </div>
        <?php if ($isContextCheckout): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        //var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>
