<?php
/**
 * @var $this Mage_Paypal_Block_Express_Shortcut
 */
 
 $shortcutHtmlId = $this->getShortcutHtmlId();
 $bmlShortcutHtmlId = $this->getBmlShortcutHtmlId();
?>
<p class="paypal-logo">
	<?php if ($this->isOrPositionBefore()): ?>
		<span class="paypal-or"><?=$this->__('-OR-');?></span>
	<?php endif; ?>
	<a data-action="checkout-form-submit" id="<?=$shortcutHtmlId ?>" href="<?=$this->getCheckoutUrl()?>">
		<img src="<?=$this->getSkinUrl('css/wsu/opc/images/paypal.png', array('_secure'=>true))?>" alt="<?=Mage::helper('paypal')->__('Checkout with PayPal');?>" title="<?=Mage::helper('paypal')->__('Checkout with PayPal');?>" />
	</a>
<?php if ($this->getIsBmlEnabled()): ?>
	<span class="paypal-or"><?=$this->__('-OR-');?></span>
</p>
	<li class="bml-checkout-type">
		<p class="paypal-logo">
		<span class="bml_button">
			<a id="<?=$bmlShortcutHtmlId ?>" href="<?=$this->getBmlCheckoutUrl()?>">
			<img src="<?=$this->getBmlImageUrl()?>" alt="<?=Mage::helper('paypal')->__('Checkout with PayPal Bill Me Later');?>" title="<?=Mage::helper('paypal')->__('Checkout with PayPal Bill Me Later');?>" />
			</a>
			<a href="<?=$this->getMarketMessageUrl()?>"><img src="<?=$this->getMarketMessage()?>" /></a>
		</span>
		</p>
	</li>
<?php else: ?>
</p>
<?php endif;?>


<?php if ($this->isOrPositionAfter()): ?>
<li>
	<p class="paypal-logo">
	<span class="paypal-or"><?=$this->__('-OR-');?></span>
	</p>
</li>
 <?php endif; ?>
<?php if ($this->getConfirmationUrl() || $this->getIsInCatalogProduct()): ?>
<?php if ($this->getIsInCatalogProduct()): ?>
	<input type="hidden" id="pp_checkout_url" name="return_url" value="" />
<?php endif; ?>
<script type="text/javascript">
//<![CDATA[
	$$('#<?=$shortcutHtmlId ?>','#<?=$bmlShortcutHtmlId ?>').invoke('observe', 'click', function(event) {
		<?php if ($this->getConfirmationUrl()): ?>
			if (confirm('<?=Mage::helper('core')->jsQuoteEscape($this->getConfirmationMessage())?>')) {
				this.href = '<?=$this->getConfirmationUrl() ?>';
			}
		<?php endif; ?>
		<?php if ($this->getIsInCatalogProduct()): ?>
			$('pp_checkout_url').value = this.href;
			productAddToCartForm.submit(this);
			event.stop();
		<?php endif; ?>
	});
//]]>
</script>
<?php endif; ?>
