(function($,WSU){
    $(document).ready(function(){
        $("[id$='click_to_save']").attr('data-action',"");
        WSU.OPC.Checkout.init();
        WSU.OPC.coupon.init();
        WSU.OPC.Comment.init();
        WSU.OPC.Agreement.init();
        WSU.OPC.Login.init();
        WSU.OPC.Decorator.initReviewBlock();
        WSU.OPC.Decorator.setActivePayment();
    });
})(jQuery,jQuery.WSU||{});
