<?php
$form="";
if($this->helper('wsu_opc')->hasCheckoutForm()){
	$form = $this->getChildHtml('webformscrf.form'); 
}
$form_location = Mage::getStoreConfig('wsu_opc/default/form_location');
$loading = '<div class="opc-ajax-loader" style="display:none;"><div class="loader"></div></div>';
?>


<script type="text/javascript"> var countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?>;</script>
<div class="opc-wrapper-opc">
	<div id="general_message"><?=$loading?></div>
	<h2><?php echo $this->__('Checkout')?></h2>
	<p><?php echo $this->__('Fill in the Fields below to complete your purchase!')?></p>
	
	<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
		<?php echo $this->getChildHtml('login');?>	
	<?php endif;?>
	<div class="clear"></div>

    <div class="opc-col-left">
		<?=($form_location=='billing_above'?$form:"")?>
		<form id="opc-address-form-billing" class="billing-block">
        	<?=$this->getChildHtml('billing')?>
			<?=$loading?>
        </form>
        <form id="opc-address-form-shipping" class="shipping-block hidden">
        	<?=$this->getChildHtml('shipping')?>
			<?=$loading?>
        </form>
		<?=($form_location=='billing_below'?$form:"")?>
    </div>

    <div class="opc-col-center">
    	<?php if (!$this->getOnepage()->getQuote()->isVirtual()):?>
    	<div class="shipping-block">
        	<h3><?=$this->__('Shipping Method')?></h3>
        	<div id="shipping-block-methods">
				<?=$this->getChildHtml('shipping_method');//$this->_getShippingMethodsHtml();?>
			</div>
			<?=$loading?>
		</div>
		<?php endif;?>
		<div class="payment-block <?php if ($this->getOnepage()->getQuote()->isVirtual()):?>clear-margin<?php endif;?>" style=" position:relative;">
			<h3><?=$this->__('Payment Method')?></h3>
			<?=$this->getChildHtml('payment')//$this->_getPaymentMethodsHtml();?>
			<?=$loading?>
		</div>
		
		<div class="discount-block">
			<h3><?=$this->__('Discount Codes')?></h3>
			<?=$this->getChildhtml('coupon');?>
			<?=$loading?>
		</div>

		<?php if(Mage::helper('wsu_opc')->isShowComment()):?>
			<?=$this->getChildhtml('customer.comment');?>
		<?php endif;?>

    </div>

    <div class="opc-col-right">
		<?=($form_location=='review_above'?$form:"")?>
        <h3><?=$this->__('Review Your Order')?></h3>
        <div id="review-block" style="position:relative;">
			<?=$this->_getReviewHtml()?>
			<?=$loading?>
		</div>
		<?=($form_location=='review_below'?$form:"")?>
    </div>
</div>
<script>
	WSU.OPC.Checkout.config = '<?php echo $this->getJsonConfig()?>';
	<?php if ($this->getOnepage()->getQuote()->isVirtual()):?>
	WSU.OPC.Checkout.isVirtual = true;
	<?php endif;?>	 
</script>

<div class="opc-message-wrapper">	
	<div class="opc-messages">
		<a class="close-message-wrapper"></a>
		<div class="opc-message-container"></div>
		<div class="opc-messages-action"><button class="button"><span><span><?php echo $this->__('Close')?></span></span></button></div>
	</div>
</div>






