<?php
$form="";
if($this->helper('wsu_opc')->hasCheckoutForm()){
	$form = $this->getChildHtml('webformscrf.form'); 
}
$form_location = Mage::getStoreConfig('wsu_opc/default/form_location');
$block_notice_update = Mage::getStoreConfig('wsu_opc/display/block_notice_update');



$loading = '<div class="opc-ajax-loader '.$block_notice_update.' " style="display:none;"><div class="loader"><div class="outer"></div><div class="inner"></div></div></div>';
?>


<script type="text/javascript">
	var countryRegions = <?=$this->helper('directory')->getRegionJson()?>;
	var update_type = "<?=$block_notice_update?>";
</script>
<div class="opc-wrapper-opc">
	<div id="general_message"><?=$loading?></div>
	<h2><?=$this->__('Checkout')?></h2>
	<p><?=$this->__('Fill in the Fields below to complete your purchase!')?></p>

    <div class="opc-col-left">
		<?=($form_location=='billing_above'?$form:"")?>
		<form id="opc-address-form-billing" class="billing-block">
        	<?=$this->getChildHtml('billing')?>
			<?=$loading?>
        </form>
        <form id="opc-address-form-shipping" class="shipping-block">
        	<?=$this->getChildHtml('shipping')?>
			<?=$loading?>
        </form>
		<?=($form_location=='billing_below'?$form:"")?>
    </div>

    <div class="opc-col-center">
    	<?php if (!$this->getOnepage()->getQuote()->isVirtual()):?>
    	<div class="shipping-method-block">
        	<h3><?=$this->__('Shipping Method')?></h3>
        	<div id="shipping-block-methods">
            	<?php //$this->_getShippingMethodsHtml();?>
				<?=$this->getChildHtml('shipping_method');//$this->_getShippingMethodsHtml();?>
			</div>
			<?=$loading?>
		</div>
		<?php endif;?>
		<div class="payment-block <?php if ($this->getOnepage()->getQuote()->isVirtual()):?>clear-margin<?php endif;?>" style=" position:relative;">
			<h3><?=$this->__('Payment Method')?></h3>
            <?php //$this->_getPaymentMethodsHtml();?>
			<?=$this->getChildHtml('payment')?>
			<?=$loading?>
		</div>
		
		<div class="discount-block">
			<h3><?=$this->__('Discount Codes')?></h3>
			<?=$this->getChildhtml('coupon');?>
			<?=$loading?>
		</div>

		<?php if(Mage::helper('wsu_opc')->isShowComment()):?>
			<?=$this->getChildhtml('customer.comment');?>
		<?php endif;?>

    </div>

    <div class="opc-col-right">
		<?=($form_location=='review_above'?$form:"")?>
        <h3><?=$this->__('Review Your Order')?></h3>
        <div id="review-block" class="review-block">
			<?=$this->_getReviewHtml()?>
			<?=$loading?>
		</div>
		<?=($form_location=='review_below'?$form:"")?>
    </div>
</div>
<script>
	WSU.OPC.Checkout.config = '<?php echo $this->getJsonConfig()?>';
	<?php if ($this->getOnepage()->getQuote()->isVirtual()):?>
	WSU.OPC.Checkout.isVirtual = true;
	<?php endif;?>	 
</script>

<div class="opc-message-wrapper">	
	<div class="opc-messages">
		<a class="close-message-wrapper"></a>
		<div class="opc-message-container"></div>
		<div class="opc-messages-action"><button class="button"><span><span><?php echo $this->__('Close')?></span></span></button></div>
	</div>
</div>






