<?php
$form="";
if($this->helper('wsu_opc')->hasCheckoutForm()){
	$form = $this->getChildHtml('webformscrf.form'); 
}
?>


<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<div class="opc-wrapper-opc">
	<h2><?php echo $this->__('Checkout')?></h2>
	<p><?php echo $this->__('Fill in the Fields below to complete your purchase!')?></p>
	
	<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
		<?php echo $this->getChildHtml('login');?>	
	<?php endif;?>
	<div class="clear"></div>

    <div class="opc-col-left">
		<?=(Mage::getStoreConfig('wsu_opc/default/form_location')=='billing_above'?$form:"")?>
		<form id="opc-address-form-billing">
        	<?php echo $this->getChildHtml('billing')?>
        </form>
        	
        <form id="opc-address-form-shipping" class="hidden">
        <?php echo $this->getChildHtml('shipping')?>
        </form>
		<?=(Mage::getStoreConfig('wsu_opc/default/form_location')=='billing_below'?$form:"")?>
    </div>

    <div class="opc-col-center">
    	<?php if (!$this->getOnepage()->getQuote()->isVirtual()):?>
    	<div class="shipping-block">
        	<h3><?php echo $this->__('Shipping Method')?></h3>
        	<div id="shipping-block-methods">
				<?php echo $this->getChildHtml('shipping_method');//$this->_getShippingMethodsHtml();?>
			</div>
		</div>
		<?php endif;?>
		<div class="payment-block <?php if ($this->getOnepage()->getQuote()->isVirtual()):?>clear-margin<?php endif;?>" style=" position:relative;">
			<h3><?php echo $this->__('Payment Method')?></h3>
			<?php echo $this->getChildHtml('payment')//$this->_getPaymentMethodsHtml();?>
			
			<div class="opc-ajax-loader">
				<div id="floatingCirclesG">
					<div class="f_circleG" id="frotateG_01"></div>
					<div class="f_circleG" id="frotateG_02"></div>
					<div class="f_circleG" id="frotateG_03"></div>
					<div class="f_circleG" id="frotateG_04"></div>
					<div class="f_circleG" id="frotateG_05"></div>
					<div class="f_circleG" id="frotateG_06"></div>
					<div class="f_circleG" id="frotateG_07"></div>
					<div class="f_circleG" id="frotateG_08"></div>
				</div>
			</div>
			
		</div>
		
		<div class="discount-block">
			<h3><?php echo $this->__('Discount Codes')?></h3>
			<?php echo $this->getChildhtml('coupon');?>
			<div class="opc-ajax-loader">
				<div id="floatingCirclesG">
					<div class="f_circleG" id="frotateG_01"></div>
					<div class="f_circleG" id="frotateG_02"></div>
					<div class="f_circleG" id="frotateG_03"></div>
					<div class="f_circleG" id="frotateG_04"></div>
					<div class="f_circleG" id="frotateG_05"></div>
					<div class="f_circleG" id="frotateG_06"></div>
					<div class="f_circleG" id="frotateG_07"></div>
					<div class="f_circleG" id="frotateG_08"></div>
				</div>
			</div>
		</div>

		<?php if(Mage::helper('wsu_opc')->isShowComment()):?>
			<?php echo $this->getChildhtml('customer.comment');?>
		<?php endif;?>

    </div>

    <div class="opc-col-right">
		<?=(Mage::getStoreConfig('wsu_opc/default/form_location')=='review_above'?$form:"")?>
        <h3><?php echo $this->__('Review Your Order')?></h3>
        <div id="review-block" style=" position:relative;">
			<?php echo $this->_getReviewHtml()?>
			<div class="opc-ajax-loader">
				<div id="floatingCirclesG">
					<div class="f_circleG" id="frotateG_01"></div>
					<div class="f_circleG" id="frotateG_02"></div>
					<div class="f_circleG" id="frotateG_03"></div>
					<div class="f_circleG" id="frotateG_04"></div>
					<div class="f_circleG" id="frotateG_05"></div>
					<div class="f_circleG" id="frotateG_06"></div>
					<div class="f_circleG" id="frotateG_07"></div>
					<div class="f_circleG" id="frotateG_08"></div>
				</div>
			</div>
		</div>
		<?=(Mage::getStoreConfig('wsu_opc/default/form_location')=='review_below'?$form:"")?>
    </div>
</div>
<script>
	WSU.OPC.Checkout.config = '<?php echo $this->getJsonConfig()?>';
	<?php if ($this->getOnepage()->getQuote()->isVirtual()):?>
	WSU.OPC.Checkout.isVirtual = true;
	<?php endif;?>	 
</script>

<!--<div class="opc-ajax-loader">
	<div id="floatingCirclesG">
		<div class="f_circleG" id="frotateG_01"></div>
		<div class="f_circleG" id="frotateG_02"></div>
		<div class="f_circleG" id="frotateG_03"></div>
		<div class="f_circleG" id="frotateG_04"></div>
		<div class="f_circleG" id="frotateG_05"></div>
		<div class="f_circleG" id="frotateG_06"></div>
		<div class="f_circleG" id="frotateG_07"></div>
		<div class="f_circleG" id="frotateG_08"></div>
	</div>
</div>-->
<div class="opc-message-wrapper">
	
	<div class="opc-messages">
		<a class="close-message-wrapper"></a>
		<div class="opc-message-container"></div>
		<div class="opc-messages-action"><button class="button"><span><span><?php echo $this->__('Close')?></span></span></button></div>
	</div>
</div>






