<?=$this->getChildHtml('items_before'); ?>
<div id="checkout-review-table-wrapper">
	<h3 class="review-title"><?=$this->__('Review Your Order')?></h3>
    <table class="opc-data-table" id="checkout-review-table">
        <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1" />
        <col width="1" />
        <?php endif; ?>
        <thead>
            <tr>
                <th rowspan="<?=$rowspan ?>"><?=$this->__('Product Name') ?></th>
                <th colspan="<?=$colspan ?>" class="a-center"><?=$this->__('Price') ?></th>
                <th rowspan="<?=$rowspan ?>" class="a-center"><?=$this->__('Qty') ?></th>
                <th colspan="<?=$colspan ?>" class="a-center"><?=$this->__('Subtotal') ?></th>
            </tr>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-right"><?=$this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?=$this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    <th class="a-right"><?=$this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?=$this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                </tr>
            <?php endif; ?>
        </thead>
        <?=$this->getChildHtml('totals');?>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?=$this->getItemHtml($_item)?>
        <?php endforeach ?>
		<tr><td   colspan="3"><a href="<?=Mage::getUrl('checkout/cart')?>" class="spine-button full" style="width: 100%; text-align: center; padding: 0.15em 0.75em;">Edit Cart</a></td></tr>
        </tbody>
    </table>
</div>
<?=$this->getChildHtml('items_after');?>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>